Update testzap.yml

diff --git a/.github/workflows/testzap.yml b/.github/workflows/testzap.yml
--- a/.github/workflows/testzap.yml
+++ b/.github/workflows/testzap.yml
@@ -1,4 +1,4 @@
-name: ZAP-API Test
+name: ZAP2
 
 on:
   push:
@@ -17,20 +17,35 @@ jobs:
 
       - name: API Test 1
         run: |
-          curl -X GET https://knowledge.dev.demo.catena-x.net --user "${{ secrets.BASIC_AUTH_USER }}:${{ secrets.BASIC_AUTH_PASSWORD }}"
+          response=$(curl -X GET https://knowledge.dev.demo.catena-x.net/conforming-agent/bind --user "${{ secrets.BASIC_AUTH_USER }}:${{ secrets.BASIC_AUTH_PASSWORD }}")
+          if [[ $response == *"authentication failure"* ]]; then
+            echo "Authentication failure: Incorrect password for the user."
+            exit 1
+          fi
 
       - name: API Test 2
         run: |
-          curl -X GET https://knowledge.dev.demo.catena-x.net --header "Authorization: Basic ${{ secrets.BASIC_AUTH_TOKEN }}"
+          response=$(curl -X GET https://knowledge.dev.demo.catena-x.net/conforming-agent/bind --header "Authorization: Basic ${{ secrets.BASIC_AUTH_TOKEN }}")
+          if [[ $response == *"authentication failure"* ]]; then
+            echo "Authentication failure: Incorrect Basic Auth token."
+            exit 1
+          fi
 
       - name: API Test 3
         run: |
-          curl -X GET https://knowledge.dev.demo.catena-x.net --header "X-Api-Key: ${{ secrets.API_KEY }}"
+          response=$(curl -X GET https://knowledge.dev.demo.catena-x.net/conforming-agent/bind --header "X-Api-Key: ${{ secrets.API_KEY }}")
+          if [[ $response == *"authentication failure"* ]]; then
+            echo "Authentication failure: Incorrect API key."
+            exit 1
+          fi
 
       - name: API Test 4
         run: |
-          curl -X GET https://knowledge.dev.demo.catena-x.net --header "Authorization: Bearer ${{ secrets.OAUTH2 }}"
-          #curl -X GET https://knowledge.dev.demo.catena-x.net/conforming-agent/bind --header "Authorization: Bearer ${{ secrets.OAUTH2 }}"
+          response=$(curl -X GET https://knowledge.dev.demo.catena-x.net/conforming-agent/bind --header "Authorization: Bearer ${{ secrets.OAUTH2 }}")
+          if [[ $response == *"authentication failure"* ]]; then
+            echo "Authentication failure: Incorrect OAuth2 token."
+            exit 1
+          fi
 
       - name: ZAP Scan
         uses: zaproxy/action-api-scan@v0.5.0
