Update testzap.yml

diff --git a/.github/workflows/testzap.yml b/.github/workflows/testzap.yml
--- a/.github/workflows/testzap.yml
+++ b/.github/workflows/testzap.yml
@@ -27,23 +27,23 @@ jobs:
           #  exit 1
           #fi
 
-          #if [[ $response == *"authentication failure"* ]]; then
-          #  echo "Authentication failure: Incorrect password for the user."
-          #  exit 1
-          #fi
+          if [[ $response == *"authentication failure"* ]]; then
+            echo "Authentication failure: Incorrect password for the user."
+            exit 1
+          fi
 
       - name: API Test 2
         run: |
           response=$(curl -w "%{http_code}" -X GET https://knowledge.dev.demo.catena-x.net --header "Authorization: Basic ${{ secrets.BASIC_AUTH_TOKEN }}")
-          echo "Response: $response"
+          #echo "Response: $response"
 
-          http_status_code=$(echo "$response" | awk '{print $NF}')
-          echo "HTTP Status Code: $http_status_code"
+          #http_status_code=$(echo "$response" | awk '{print $NF}')
+          #echo "HTTP Status Code: $http_status_code"
 
-          if [[ $http_status_code -ne 200 ]]; then
-            echo "Error: HTTP request failed with status code $http_status_code"
-            exit 1
-          fi
+          #if [[ $http_status_code -ne 200 ]]; then
+          #  echo "Error: HTTP request failed with status code $http_status_code"
+          #  exit 1
+          #fi
 
           if [[ $response == *"authentication failure"* ]]; then
             echo "Authentication failure: Incorrect Basic Auth token."
@@ -55,9 +55,9 @@ jobs:
           response=$(curl -X GET https://knowledge.dev.demo.catena-x.net --header "X-Api-Key: ${{ secrets.API_KEY }}")
           #echo "Response: $response"
 
-           # Extract the HTTP status code
-          http_status_code=$(echo "$response" | tr -d -c '0-9')
-          echo "HTTP Status Code: $http_status_code"
+          # Extract the HTTP status code 
+          #http_status_code=$(echo "$response" | tr -d -c '0-9')
+          #echo "HTTP Status Code: $http_status_code"
           
           if [[ $response == *"authentication failure"* ]]; then
             echo "Authentication failure: Incorrect API key."
@@ -69,9 +69,9 @@ jobs:
           response=$(curl -X GET https://knowledge.dev.demo.catena-x.net --header "Authorization: Bearer ${{ secrets.OAUTH2 }}")
           #echo "Response: $response"
 
-           # Extract the HTTP status code
-          http_status_code=$(echo "$response" | tr -d -c '0-9')
-          echo "HTTP Status Code: $http_status_code"
+          # Extract the HTTP status code
+          #http_status_code=$(echo "$response" | tr -d -c '0-9')
+          #echo "HTTP Status Code: $http_status_code"
           
           if [[ $response == *"authentication failure"* ]]; then
             echo "Authentication failure: Incorrect OAuth2 token."
