Update testzap.yml

diff --git a/.github/workflows/testzap.yml b/.github/workflows/testzap.yml
--- a/.github/workflows/testzap.yml
+++ b/.github/workflows/testzap.yml
@@ -1,48 +1,121 @@
-name: ZAP Scans
+name: ZAP test
 
-on: [push]
+on:
+  push:
+    branches:
+      - main
 
 jobs:
-  zap_scan1:
+  zap_full_scan:
     runs-on: ubuntu-latest
-    outputs:
-      id: ${{ steps.zap_scan1.outputs.id }}
+    name: OWASP ZAP Full Scan
+    
     steps:
-      - name: ZAP Scan 1
-        id: zap_scan1
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          ref: main
+          fetch-depth: 0
+
+      - name: ZAP Full Scan 
+        id: zap_full_scan
         uses: zaproxy/action-full-scan@v0.8.0
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
-          target: 'https://knowledge.dev.demo.catena-x.net'  # Specify the target URL for scan 1
+          target: 'https://knowledge.dev.demo.catena-x.net'  # Please specify the target URL to be scanned
         env:
-          ZAP_REPORT_DIR: ${{ github.workspace }}/zap-scan1-results
+          ZAP_REPORT_DIR: ${{ github.workspace }}/zap-full-scan-results
+          
       - name: Save output variables
-        run: echo "zap_scan1_results=$ID" >> $GITHUB_ENV
+        run: echo "zap-full-scan-results=$ID" >> $GITHUB_ENV
 
-  zap_scan2:
+  zap_api_scan:
     runs-on: ubuntu-latest
-    outputs:
-      id: ${{ steps.zap_scan2.outputs.id }}
+    name: OWASP ZAP API Scan
+    
     steps:
-      - name: ZAP Scan 2
-        id: zap_scan2
-        uses: zaproxy/action-full-scan@v0.8.0
+      - name: Checkout
+        uses: actions/checkout@v2
         with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
-          target: 'https://example.com'  # Specify the target URL for scan 2
-        env:
-          ZAP_REPORT_DIR: ${{ github.workspace }}/zap-scan2-results
-      - name: Save output variables
-        run: echo "zap_scan2_results=$ID" >> $GITHUB_ENV
+          ref: main
+          fetch-depth: 0
 
-  process_results:
-    needs: [zap_scan1, zap_scan2]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Process Results
+      - name: API Test 1
+        id: api_test_1
         run: |
-          echo "Results of ZAP Scan 1: $zap_scan1_results"
-          echo "Results of ZAP Scan 2: $zap_scan2_results"
-          echo "Combined Results: $zap_scan1_results $zap_scan2_results" >> "$GITHUB_OUTPUT"
+          # Perform API Test 1 and capture the response
+          response=$(curl -w "%{http_code}" -v GET https://knowledge.dev.demo.catena-x.net --user "${{ secrets.BASIC_AUTH_USER }}:${{ secrets.BASIC_AUTH_PASSWORD }}")
+          echo "Response: $response"
+      - name: API Test 2
+        id: api_test_2
+        run: |
+          # Perform API Test 2 and capture the response
+          response=$(curl -w "%{http_code}" -X GET https://knowledge.dev.demo.catena-x.net --header "Authorization: Basic ${{ secrets.BASIC_AUTH_TOKEN }}")
+          echo "Response: $response"
+          
+      - name: API Test 3
+        id: api_test_3
+        run: |
+          # Perform API Test 3 and capture the response
+          response=$(curl -X GET https://knowledge.dev.demo.catena-x.net --header "X-Api-Key: ${{ secrets.API_KEY }}")
+          echo "Response: $response"
+          
+      - name: API Test 4
+        id: api_test_4
+        run: |
+          # Perform API Test 4 and capture the response
+          response=$(curl -X GET https://knowledge.dev.demo.catena-x.net --header "Authorization: Bearer ${{ secrets.OAUTH2 }}")
+          echo "Response: $response"
+          
+      - name: ZAP API Scan
+        id: zap_api_scan
+        uses: zaproxy/action-api-scan@v0.5.0
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
+          format: openapi
+          target: 'https://knowledge.dev.demo.catena-x.net'
+        env:
+          ZAP_REPORT_DIR: ${{ github.workspace }}/zap-api-scan-results
+
+      - name: Save output variables
+        run: echo "zap-api-scan-results=$ID" >> $GITHUB_ENV
+
+analyze_results:
+  needs: [zap_full_scan, zap_api_scan]
+  runs-on: ubuntu-latest
+  steps:
+    - name: Debug
+      run: |
+        ls -R ${{ github.workspace }}
+
+    - name: Check ZAP Full Scan Results
+      run: |
+        if [ -d "${{ github.workspace }}/zap-full-scan-results" ] && [ "$(ls -A ${{ github.workspace }}/zap-full-scan-results)" ]; then
+          echo "ZAP Full Scan Results are present."
+        else
+          echo "ZAP Full Scan Results are missing or empty."
+          exit 1
+        fi
+
+    - name: Archive ZAP Full Scan Results
+      uses: actions/upload-artifact@v2
+      with:
+        name: zap-full-scan-results
+        path: ${{ github.workspace }}/zap-full-scan-results
+
+    - name: Check ZAP API Scan Results
+      run: |
+        if [ -d "${{ github.workspace }}/zap-api-scan-results" ] && [ "$(ls -A ${{ github.workspace }}/zap-api-scan-results)" ]; then
+          echo "ZAP API Scan Results are present."
+        else
+          echo "ZAP API Scan Results are missing or empty."
+          exit 1
+        fi
+
+    - name: Archive ZAP API Scan Results
+      uses: actions/upload-artifact@v2
+      with:
+        name: zap-api-scan-results
+        path: ${{ github.workspace }}/zap-api-scan-results
